FROM golang:1.16-alpine AS builder

WORKDIR /usr/src/app

COPY . .

#RUN go build
RUN CGO_ENABLED=0 go build -o server

FROM scratch

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/server /app/server

USER 1001

EXPOSE 8080

CMD ["/app/server"]