
FROM node:16-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:16-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/build ./build

RUN npm install -g serve && \
    adduser --system --no-create-home appuser && \
    chown appuser .

USER appuser

EXPOSE 5000

CMD ["serve", "-s", "-l", "5000", "build"]
