FROM node:16-alpine

EXPOSE 5000

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build && \
    npm install -g serve && \
    adduser --system --no-create-home appuser && \
    chown appuser . 

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]

