
name: Release Flask app

on:
  push:
    paths:
      - 'part3/ex3_2/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./part3/ex3_2/
          file: ./part3/ex3_2/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ex3-2-app:latest

      - 
        name: Pull the image to the server
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: 
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ex3-2-app:latest && docker stop ex3-2-app && docker rm ex3-2-app && docker run -d -p 5000:5000 --name ex3-2-app ${{ secrets.DOCKERHUB_USERNAME }}/ex3-2-app:latest