
name: Release NodeJS app

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      # Checkout to the repository
      - 
        uses: actions/checkout@v2
      # Login to Docker Hub  
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build the image
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: syrvil/ex3_1_app:latest

