
name: Release NodeJS app

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./part3/ex3_1/express-app
          file: ./part3/ex3_1/express-app/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ex3-1-app:latest

